apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-web-svc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-web-svc
    spec:
      containers:
      - name: node-web-svc
        image: myresourceg.azurecr.io/node-web-svc:v1
        ports:
        - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: node-web-svc
spec:
  type: LoadBalancer
  ports:
  - port: 9002
  selector:
    app: node-web-svc
